// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/v1/message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // 消息唯一ID (MongoDB ObjectID)
	ConversationID string                 `protobuf:"bytes,2,opt,name=conversationID,proto3" json:"conversationID,omitempty"`        // 会话ID (MongoDB ObjectID)
	SenderID       string                 `protobuf:"bytes,3,opt,name=senderID,proto3" json:"senderID,omitempty"`                    // 发送消息用户ID
	Timestamp      int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // 消息发送时间
	ContentType    int32                  `protobuf:"varint,5,opt,name=contentType,proto3" json:"contentType,omitempty"`             // 1=text, 2=image, 3=file, 4=voice
	Body           *anypb.Any             `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`                            // 消息内容
	Metadata       *MessageMetadata       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`                    // 元数据
	DeletedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"` // 删除时间
	// The following fields are for client display purposes and are not stored in the database.
	SenderName    string `protobuf:"bytes,9,opt,name=senderName,proto3" json:"senderName,omitempty"`     // 发送消息用户的用户名
	Avatar        string `protobuf:"bytes,10,opt,name=avatar,proto3" json:"avatar,omitempty"`            // 头像
	MessageType   int32  `protobuf:"varint,11,opt,name=messageType,proto3" json:"messageType,omitempty"` // 消息类型，1.单聊 2.群聊
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *Message) GetSenderID() string {
	if x != nil {
		return x.SenderID
	}
	return ""
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *Message) GetBody() *anypb.Any {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Message) GetMetadata() *MessageMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Message) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Message) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *Message) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Message) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

// TextBody is used for text messages, and it's packed into the 'body' field of the Message.
type TextBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextBody) Reset() {
	*x = TextBody{}
	mi := &file_api_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextBody) ProtoMessage() {}

func (x *TextBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextBody.ProtoReflect.Descriptor instead.
func (*TextBody) Descriptor() ([]byte, []int) {
	return file_api_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *TextBody) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// FileAttachment is used for file/image/voice messages, and it's packed into the 'body' field of the Message.
type FileAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`           // MinIO/S3 的 URL
	FileName      string                 `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"` // "简历.pdf"
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`        // 文件大小 (bytes)
	MimeType      string                 `protobuf:"bytes,4,opt,name=mimeType,proto3" json:"mimeType,omitempty"` // "image/jpeg"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileAttachment) Reset() {
	*x = FileAttachment{}
	mi := &file_api_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAttachment) ProtoMessage() {}

func (x *FileAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAttachment.ProtoReflect.Descriptor instead.
func (*FileAttachment) Descriptor() ([]byte, []int) {
	return file_api_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *FileAttachment) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FileAttachment) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileAttachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileAttachment) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// MessageMetadata 用于存储回复、@ 等元数据
type MessageMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyToMsgID  string                 `protobuf:"bytes,1,opt,name=replyToMsgID,proto3" json:"replyToMsgID,omitempty"` // 回复的消息 ID (用 string 存 ObjectID)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageMetadata) Reset() {
	*x = MessageMetadata{}
	mi := &file_api_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageMetadata) ProtoMessage() {}

func (x *MessageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageMetadata.ProtoReflect.Descriptor instead.
func (*MessageMetadata) Descriptor() ([]byte, []int) {
	return file_api_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *MessageMetadata) GetReplyToMsgID() string {
	if x != nil {
		return x.ReplyToMsgID
	}
	return ""
}

var File_api_v1_message_proto protoreflect.FileDescriptor

const file_api_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x14api/v1/message.proto\x12\x02v1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x03\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0econversationID\x18\x02 \x01(\tR\x0econversationID\x12\x1a\n" +
	"\bsenderID\x18\x03 \x01(\tR\bsenderID\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12 \n" +
	"\vcontentType\x18\x05 \x01(\x05R\vcontentType\x12(\n" +
	"\x04body\x18\x06 \x01(\v2\x14.google.protobuf.AnyR\x04body\x12/\n" +
	"\bmetadata\x18\a \x01(\v2\x13.v1.MessageMetadataR\bmetadata\x129\n" +
	"\n" +
	"deleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x1e\n" +
	"\n" +
	"senderName\x18\t \x01(\tR\n" +
	"senderName\x12\x16\n" +
	"\x06avatar\x18\n" +
	" \x01(\tR\x06avatar\x12 \n" +
	"\vmessageType\x18\v \x01(\x05R\vmessageType\"$\n" +
	"\bTextBody\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"n\n" +
	"\x0eFileAttachment\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\bfileName\x18\x02 \x01(\tR\bfileName\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1a\n" +
	"\bmimeType\x18\x04 \x01(\tR\bmimeType\"5\n" +
	"\x0fMessageMetadata\x12\"\n" +
	"\freplyToMsgID\x18\x01 \x01(\tR\freplyToMsgIDB\x17Z\x15MyGoChat/pkg/pb/v1;pbb\x06proto3"

var (
	file_api_v1_message_proto_rawDescOnce sync.Once
	file_api_v1_message_proto_rawDescData []byte
)

func file_api_v1_message_proto_rawDescGZIP() []byte {
	file_api_v1_message_proto_rawDescOnce.Do(func() {
		file_api_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_message_proto_rawDesc), len(file_api_v1_message_proto_rawDesc)))
	})
	return file_api_v1_message_proto_rawDescData
}

var file_api_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_message_proto_goTypes = []any{
	(*Message)(nil),               // 0: v1.Message
	(*TextBody)(nil),              // 1: v1.TextBody
	(*FileAttachment)(nil),        // 2: v1.FileAttachment
	(*MessageMetadata)(nil),       // 3: v1.MessageMetadata
	(*anypb.Any)(nil),             // 4: google.protobuf.Any
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_api_v1_message_proto_depIdxs = []int32{
	4, // 0: v1.Message.body:type_name -> google.protobuf.Any
	3, // 1: v1.Message.metadata:type_name -> v1.MessageMetadata
	5, // 2: v1.Message.deleted_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_message_proto_init() }
func file_api_v1_message_proto_init() {
	if File_api_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_message_proto_rawDesc), len(file_api_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_message_proto_goTypes,
		DependencyIndexes: file_api_v1_message_proto_depIdxs,
		MessageInfos:      file_api_v1_message_proto_msgTypes,
	}.Build()
	File_api_v1_message_proto = out.File
	file_api_v1_message_proto_goTypes = nil
	file_api_v1_message_proto_depIdxs = nil
}
